CREATE TABLE TYPE_DEVICES(
	TYPE_DEVICE NVARCHAR(50) NOT NULL,
	DESCRIPTION NVARCHAR(100) NOT NULL,
	MODEL NVARCHAR(50) NOT NULL,
	PART NVARCHAR(50) NOT NULL,
	QUANTITY INT NOT NULL
);

 ALTER TABLE TYPE_DEVICES
        ADD CONSTRAINT XPKTYPEDEVICES PRIMARY KEY (TYPE_DEVICE, 
               MODEL, PART);

 CREATE TABLE COMPONENTS(
 	PART_CODE NVARCHAR(50) NOT NULL,
 	DESCRIPTION NVARCHAR(100) NOT NULL,
 	COST DECIMAL(28,8) NOT	 NULL,
 	STOCK INT
 	);

  ALTER TABLE COMPONENTS
        ADD CONSTRAINT XPKCOMPONENTS PRIMARY KEY (PART_CODE);


 CREATE TABLE PLANS(
	 MODEL NVARCHAR(50) NOT NULL,
 	PLANS INT NOT NULL
 	);

		 ALTER TABLE PLANS
        ADD CONSTRAINT XPKPLANS PRIMARY KEY (MODEL);


 CREATE TABLE MAXIMUN_COST(
	 MODEL NVARCHAR(50) NOT NULL,
 	MAX_COST DECIMAL(28,8) NOT NULL
 	);

		 ALTER TABLE MAXIMUN_COST
        ADD CONSTRAINT XPKMAXIMUNCOST PRIMARY KEY (MODEL);